---
- name: Process all docker and appdata files
  block:
    - name: Initialize file lists
      ansible.builtin.set_fact:
        docker_compose_files: []
        docker_compose_appdata_files: []
        private: yes

    - name: Gather compose files
      ansible.builtin.set_fact:
        docker_compose_files: "{{ (lookup('ansible.builtin.filetree', playbook_dir + '/' + docker_dir + '/' + inventory_group_name + '/') | 
                                selectattr('state', 'ne', 'directory') |
                                selectattr('path', 'regex', '(.*/)*((docker-compose.*|.env.*)\\.j2)$') |
                                rejectattr('path', 'regex', '.*/appdata/.*') |
                                list) }}"
      run_once: true

    - name: Debug found compose files
      ansible.builtin.debug:
        msg: |
          Found compose files:
          {% for item in (docker_compose_files | unique) %}
          {{ item.src }} -> {{ docker_home_compose_path }}/{{ item.path | regex_replace('^' + inventory_group_name + '/', '') | regex_replace('\\.j2$', '') }}
          {% endfor %}
      when: docker_compose_debug_print | bool

    - name: Gather appdata files
      ansible.builtin.set_fact:
        docker_compose_appdata_files: "{{ (lookup('ansible.builtin.filetree', playbook_dir + '/' + docker_dir + '/' + inventory_group_name + '/') | 
                                        selectattr('state', 'ne', 'directory') |
                                        selectattr('path', 'regex', '.*/appdata/.*\\.j2$') |
                                        list) }}"
      run_once: true

    - name: Debug found appdata files
      ansible.builtin.debug:
        msg: |
          Found appdata files:
          {% for item in (docker_compose_appdata_files | unique) %}
          {{ item.src }} -> {{ docker_appdata_path }}/{{ item.path | regex_replace('/appdata/', '/') | regex_replace('\\.j2$', '') }}
          {% endfor %}
      when: docker_compose_debug_print | bool

    - name: Halt after debug if debug halt is enabled
      ansible.builtin.fail:
        msg: "Halting after debug output as requested"
      when: docker_compose_debug_halt | bool

    - name: Ensure base docker compose directory exists
      ansible.builtin.file:
        path: "{{ docker_home_compose_path }}"
        state: directory
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: '0755'

    - name: Ensure application-specific directories exist
      ansible.builtin.file:
        path: "{{ docker_home_compose_path }}/{{ item.path | regex_replace('^' + inventory_group_name + '/', '') | dirname }}"
        state: directory
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: '0755'
      loop: "{{ docker_compose_files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Template compose files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ docker_home_compose_path }}/{{ item.path | regex_replace('^' + inventory_group_name + '/', '') | regex_replace('\\.j2$', '') }}"
        force: yes
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: '0644'
      loop: "{{ docker_compose_files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Create appdata directories
      ansible.builtin.file:
        path: "{{ docker_appdata_path }}/{{ item.path | regex_replace('/appdata/', '/') | dirname }}"
        state: directory
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: "0755"
      loop: "{{ docker_compose_appdata_files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Template appdata files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ docker_appdata_path }}/{{ item.path | regex_replace('/appdata/', '/') | regex_replace('\\.j2$', '') }}"
        force: yes
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: "0644"
      loop: "{{ docker_compose_appdata_files }}"
      loop_control:
        label: "{{ item.path }}"
