---
- debug:
    var: local_stack_path
  when: docker_compose_debug_print | bool

- name: Process all docker and appdata files
  block:
    - name: Gather compose files
      ansible.builtin.find:
        paths: 
          - "{{ local_stack_path }}"
        patterns: 
          - "Dockerfile"
          - "docker-compose*.yml.j2"
          - ".env.j2"
        excludes: 
          - "*appdata*"
          - "docker-compose.override.yml.j2"
        hidden: true
        file_type: file
        recurse: yes
      become: false
      delegate_to: localhost
      register: found_compose_files
      changed_when: false

    - name: Debug found compose files
      ansible.builtin.debug:
        msg: |
          Found compose files:
          {% for file in found_compose_files.files %}
          - {{ file.path }}
          {% endfor %}
      when: docker_compose_debug_print | bool

    - name: Gather appdata files  
      ansible.builtin.set_fact:
        found_appdata_files: "{{ (lookup('ansible.builtin.filetree', playbook_dir + '/' + docker_dir + '/' + inventory_group_name + '/' + current_stack_name + '/') | 
                                  selectattr('state', 'ne', 'directory') |
                                  selectattr('path', 'regex', '.*/appdata/.*\\.j2$') |
                                  list) }}"
      become: false
      delegate_to: localhost
      changed_when: false

    - name: Debug found appdata files
      ansible.builtin.debug:
        msg: |
          Found appdata files:
          {% for item in (found_appdata_files | unique) %}
          {{ item.src }} -> {{ docker_appdata_path }}/{{ item.path | regex_replace('/appdata/', '/') | regex_replace('\\.j2$', '') }}
          {% endfor %}
      when: docker_compose_debug_print | bool

    - name: Halt after debug if debug halt is enabled
      ansible.builtin.fail:
        msg: "Halting after debug output as requested"
      when: docker_compose_debug_halt | bool

    - name: Ensure base docker compose directory exists
      ansible.builtin.file:
        path: "{{ docker_compose_path }}/{{ current_stack_name }}"
        state: directory
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: '0755'

    - name: Ensure application-specific directories exist
      ansible.builtin.file:
        path: "{{ docker_compose_path }}/{{ current_stack_name }}/{{ item.path | regex_replace('.*/' + inventory_group_name + '/' + current_stack_name + '/?', '') | dirname }}"
        state: directory
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: '0755'
      loop: "{{ found_compose_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Template compose files
      ansible.builtin.template:
        src: "{{ item.path }}"
        dest: "{{ docker_compose_path }}/{{ current_stack_name }}/{{ item.path | regex_replace('.*/' + inventory_group_name + '/' + current_stack_name + '/?', '') | regex_replace('\\.j2$', '') }}"
        force: yes
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: '0644'
      loop: "{{ found_compose_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Create appdata directories
      ansible.builtin.file:
        path: "{{ docker_appdata_path }}/{{ item.path | regex_replace('/appdata/', '/') | dirname }}"
        state: directory
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: "0755"
      loop: "{{ found_appdata_files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Template appdata files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ docker_appdata_path }}/{{ item.path | regex_replace('/appdata/', '/') | regex_replace('\\.j2$', '') }}"
        force: yes
        owner: "{{ appdata_owner | default('1000') }}"
        group: "{{ appdata_group | default('1000') }}"
        mode: "0644"
      loop: "{{ found_appdata_files }}"
      loop_control:
        label: "{{ item.path }}"
