---
- name: Initialize file lists
  ansible.builtin.set_fact:
    services: []
    private: yes

- name: Parse include section from root docker-compose.yml.j2
  ansible.builtin.set_fact:
    include_paths: >-
      {{
        (lookup('ansible.builtin.template', playbook_dir + '/' + docker_dir + '/' + inventory_group_name + '/docker-compose.yml.j2') | from_yaml).include
        | map(attribute='path')
        | map('regex_replace', '^(\.\/)?', playbook_dir + '/' + docker_dir + '/' + inventory_group_name + '/')
        | map('regex_replace', '$', '.j2')
        | list
      }}
  run_once: true

- name: Debug include paths
  ansible.builtin.debug:
    var: include_paths
  when: docker_compose_debug_print | bool

- name: Gather service names from files
  ansible.builtin.set_fact:
    services: "{{ services + (lookup('ansible.builtin.template', item) | from_yaml).services.keys() | list }}"
  with_items: "{{ include_paths }}"
  when: "(lookup('ansible.builtin.template', item) | from_yaml).services is defined"
  run_once: true

- name: Debug gathered services
  ansible.builtin.debug:
    var: services
  when: docker_compose_debug_print | bool

- name: Extend and template compose override
  ansible.builtin.template:
    src: "{{ playbook_dir }}/{{ docker_dir }}/{{ inventory_group_name }}/docker-compose.override.yml.j2"
    dest: "{{ docker_home_compose_path }}/docker-compose.override.yml"
    mode: "0644"
  vars:
    services: "{{ services | unique }}"