---
- name: Debug docker path
  ansible.builtin.debug:
    msg: "Looking for docker-compose files in: {{ docker_compose_path }}"

- name: Start Docker stack for {{ inventory_group_name }}/{{ current_stack_name }}
  become: yes
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}/{{ current_stack_name }}"
    state: present
    recreate: "auto"
    env_files:
    - .env
    files:
    - docker-compose.yml
    - docker-compose.override.yml
    remove_orphans: true
  register: compose_output
  when: docker_compose_start_stack | bool

- name: Show compose-up results
  ansible.builtin.debug:
    msg: |
      Container Status:
      {% for container in compose_output.containers %}
      - Container: {{ container.Name }}
        Networks: {{ container.Networks | join(', ') }}
        Status: {{ container.State }} (Status: {{ container.Status }})
      {% endfor %}
  when: (docker_compose_start_stack | bool) and (docker_compose_show_status | bool)

- name: Prune
  community.docker.docker_prune:
    containers: false
    images: true
    networks: false
    volumes: false
    builder_cache: false
  register: prune_output

- name: Show prune results
  ansible.builtin.debug:
    msg: "{{ prune_output }}"
