---
- name: Find stacks for current group
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/{{ docker_dir }}/{{ inventory_group_name }}"
    file_type: directory
    recurse: no
  become: false
  delegate_to: localhost
  register: found_stacks
  changed_when: false

- debug:
    var: found_stacks
  when: docker_compose_debug_print | bool

- name: Build ordered stack list
  ansible.builtin.set_fact:
    ordered_stack_names: >-
      {{ (docker_stack_order[inventory_group_name] | default([]) | intersect(found_stack_names)) +
         (found_stack_names | difference(docker_stack_order[inventory_group_name] | default([]))) }}
  vars:
    found_stack_names: "{{ found_stacks.files | map(attribute='path') | map('basename') | list }}"

- debug:
    var: ordered_stack_names
  when: docker_compose_debug_print | bool

- name: Filter stacks by name
  ansible.builtin.set_fact:
    ordered_stack_names: "{{ ordered_stack_names | select('equalto', docker_compose_stack_filter) | list }}"
  when: docker_compose_stack_filter != ''

- name: Process stacks
  include_tasks: process_stack.yml
  loop: "{{ ordered_stack_names }}"
  loop_control:
    loop_var: current_stack_name
  vars:
    local_stack_path: "{{ playbook_dir }}/{{ docker_dir }}/{{ inventory_group_name }}/{{ current_stack_name }}"
