---
collections:
  - name: arillso.system
    version: 0.0.34
  - name: devsec.hardening
    version: 9.0.1

roles:
  - name: fuzzymistborn.autorestic
    version: v0.3.2
  - name: geerlingguy.docker
    version: 7.3.0
  - name: geerlingguy.nfs
    version: 2.0.0
  - name: geerlingguy.pip
    version: 3.0.3
  - name: grog.package
    version: v1.4.1
  - name: IronicBadger.proxmox_nag_removal
    version: 1.0.2
  - name: joenyland.plexmediaserver
    version: main
  - name: tigattack.mergerfs
    version: 1.3.1