---
# ansible-galaxy install -r requirements.yml --force

collections:
  - name: arillso.system
    version: 0.0.36
  - name: devsec.hardening
    version: 9.0.1
  - name: community.proxmox
    version: 1.3.0
  - name: community.docker
    version: 4.7.0
  - name: community.general
    version: 11.2.1
  - name: ansible.posix
    version: 1.6.2

roles:
  - name: fuzzymistborn.autorestic
    version: v0.3.2
  - name: geerlingguy.docker
    version: 7.4.7
  - name: geerlingguy.nfs
    version: 2.1.0
  - name: geerlingguy.pip
    version: 3.1.0
  - name: grog.package
    version: v1.4.1
  - name: IronicBadger.proxmox_nag_removal
    version: 1.0.2
  - name: joenyland.plexmediaserver
    version: main
  - name: tigattack.mergerfs
    version: 2.1.0