---

- hosts: neo
  # gather_facts: no
  roles:
    - role: arillso.system.users
      become: yes
    - role: grog.package
      become: yes
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: jhaycr.luks_disks
      tags: disks
    - role: jhaycr.snapraid
      become: yes
      tags: disks
    - role: tigattack.mergerfs
      tags: disks
    - role: jhaycr-local.safe_shutdown
      tags: disks
    - role: geerlingguy.nfs
    - role: jhaycr-local.backup
      become: yes
    - role: jhaycr-local.logrotate
      become: yes
    - role: jhaycr-local.docker_compose
      tags: compose
      become: yes
    - role: joenyland.plexmediaserver
    - role: jhaycr-local.plex
      become: yes
    - role: IronicBadger.proxmox_nag_removal
    - role: jhaycr-local.hetrixtools_agent
      become: yes

  tasks:
    - name: Ensure that downloads directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ nas_download_path }}"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: directory

    - name: Ensure that downloads directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ nas_download_path }}/usenet/completed"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: directory

    - name: Ensure that downloads directory exists
      become: yes
      ansible.builtin.file:
        path: "{{ nas_download_path }}/usenet/incomplete-downloads"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: directory

    # https://www.reddit.com/r/gluetun/comments/1ckf1jv/how_to_force_gluetun_to_rotate_to_a_new_endpoint/
    # https://github.com/qdm12/gluetun/issues/2236
    - name: Schedule gluetun rotation
      become: yes
      cron:
        name: gluetun cron
        # job: "bash -lc; /usr/local/bin/autorestic -c /home/{{ main_username }}/.autorestic.yml backup -avv --ci >> /var/log/autorestic.log 2>&1"
        job: "sudo docker exec -ti gluetun 'wget' '-qO-' '--method=PUT' '--body-data={\"status\":\"stopped\"}' 'http://127.0.0.1:8000/v1/openvpn/status'"
        user: "root"
        weekday: "*"
        month: "*"
        day: "*"
        hour: "8"
        minute: "0"
        state: present
      
- hosts: morpheus
  roles:
    - role: IronicBadger.proxmox_nag_removal
    - role: geerlingguy.docker
    - role: jhaycr-local.docker_compose
      tags: compose

- hosts: trinity
  roles:
    - role: grog.package
      become: yes
    - role: jhaycr-local.docker_compose
      tags: compose
      become: yes

  tasks:
    - name: Install Snaps
      become: yes
      community.general.snap:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        channel: "{{ item.channel | default('stable') }}"
        classic: "{{ item.classic | default(false) }}"
        dangerous: "{{ item.dangerous | default(false) }}"
      with_items: "{{ snap_list }}"

    - name: Install flatpaks
      become: yes
      community.general.flatpak:
        name: "{{ item.name }}"
        method: "{{ item.method | default('system') }}"
        no_dependencies: "{{ item.no_dependencies | default('false') }}"
        remote: "{{ item.remote | default('flathub') }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ flatpak_list }}"

    - name: Swappiness to 10%
      become: yes
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '10'
        state: present
