---

- hosts: neo

  roles:
    - role: arillso.system.users
      become: yes
    - role: grog.package
      become: yes
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: jhaycr.luks_disks
    - role: IronicBadger.snapraid
      become: yes
    - role: tigattack.mergerfs
    - role: geerlingguy.nfs
    - role: jhaycr-local.backup
      become: yes
    - role: jhaycr-local.docker_compose
      tags: compose
      become: yes
    - role: jhaycr-local.docker_appdata_ownership
      tags: compose
      become: yes
    - role: joenyland.plexmediaserver
    - role: IronicBadger.proxmox_nag_removal

  tasks:
    - name: create downloads directory
      ansible.builtin.file:
        path: "/home/{{ main_username }}/downloads"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: directory

    - name: create symbolic link to downloads
      ansible.builtin.file:
        src: "/home/{{ main_username }}/downloads"
        dest: "/mnt/storage/downloads"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: link

    - name: start docker stack
      become: yes
      tags: compose
      community.docker.docker_compose_v2:
        project_src: "{{ docker_home_compose_path }}"
        state: present
        env_files:
        - .env
        files:
        - docker-compose.yml
        - docker-compose.override.yml
        remove_orphans: true
      