---

- hosts: neo

  roles:
    - role: arillso.system.users
      become: yes
    - role: grog.package
      become: yes
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: jhaycr.luks_disks
    - role: IronicBadger.snapraid
      become: yes
    - role: tigattack.mergerfs
    - role: geerlingguy.nfs
    - role: jhaycr-local.backup
      become: yes
    - role: jhaycr-local.docker_compose
      tags: compose
      become: yes
    #- role: jhaycr-local.docker_compose_v2
    #  tags: compose
    #  become: yes
    - role: joenyland.plexmediaserver
    - role: jhaycr-local.plex
      become: yes
    - role: IronicBadger.proxmox_nag_removal

  tasks:
    - name: create downloads directory
      ansible.builtin.file:
        path: "/home/{{ main_username }}/downloads"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: directory

    - name: create symbolic link to downloads
      ansible.builtin.file:
        src: "/home/{{ main_username }}/downloads"
        dest: "/mnt/storage/downloads"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: link
      
- hosts: morpheus
  roles:
    - role: IronicBadger.proxmox_nag_removal
    - role: geerlingguy.docker
    - role: jhaycr-local.docker_compose
      tags: compose

- hosts: trinity
  roles:
    - role: grog.package
      become: yes

  tasks:
    - name: Install Snaps
      become: yes
      community.general.snap:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        channel: "{{ item.channel | default('stable') }}"
        classic: "{{ item.classic | default(false) }}"
        dangerous: "{{ item.dangerous | default(false) }}"
      with_items: "{{ snap_list }}"

    - name: Install flatpaks
      become: yes
      community.general.flatpak:
        name: "{{ item.name }}"
        method: "{{ item.method | default('system') }}"
        no_dependencies: "{{ item.no_dependencies | default('false') }}"
        remote: "{{ item.remote | default('flathub') }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ flatpak_list }}"

    - name: Swappiness to 10%
      become: yes
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '10'
        state: present