---

- hosts: neo

  roles:
    - role: arillso.system.users
      become: yes
    - role: grog.package
      become: yes
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: jhaycr.luks_disks
    - role: IronicBadger.snapraid
      become: yes
    - role: tigattack.mergerfs
    - role: geerlingguy.nfs
    - role: IronicBadger.docker_compose_generator
      tags: compose
      become: yes
    - role: IronicBadger.proxmox_nag_removal

  tasks:
    - name: create downloads directory
      ansible.builtin.file:
        path: "/home/{{ main_username }}/downloads"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: directory

    - name: create symbolic link to downloads
      ansible.builtin.file:
        src: "/home/{{ main_username }}/downloads"
        dest: "/mnt/storage/downloads"
        owner: "{{ main_username }}"
        group: "{{ main_username }}"
        state: link

    - name: deploy Docker Compose stack
      become_user: "{{ main_username }}"
      tags: compose
      community.docker.docker_compose_v2:
        project_src: "{{docker_compose_generator_output_path}}"
        files:
        - docker-compose.yml
        remove_orphans: true
      