---
- name: Create local backup dirs
  ansible.builtin.file:
    path: "{{ backup_path_local }}"
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    state: directory

- name: Set up autorestic
  ansible.builtin.import_role:
    name: fuzzymistborn.autorestic

- name: Schedule autorestic cron (hourly)
  cron:
    name: autorestic cron
    job: "/usr/local/bin/autorestic -c /home/{{ main_username }}/.autorestic.yml --ci cron >> /var/log/autorestic.log 2>&1"
    user: "root"
    weekday: "*"
    month: "*"
    day: "*"
    hour: "*"
    minute: "0"
    state: present