---
- name: create local backup dirs
  ansible.builtin.file:
    path: "{{ backup_path_local }}"
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    state: directory

- name: set up autorestic
  ansible.builtin.import_role:
    name: fuzzymistborn.autorestic
