- name: Clone VM from template
  community.proxmox.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ item.node }}"
    vmid: "{{ item.vmid }}"
    name: "{{ item.name }}"
    clone: "{{ item.template_vmid }}"
    full: true
    cores: "{{ item.cores }}"
    memory: "{{ item.memory }}"
    net: "{{ item.net }}"
    pool: "{{ item.pool | default(omit) }}"
    sshkeys: "{{ item.sshkeys | default(omit) }}"
    ciuser: "{{ item.ciuser }}"
    cipassword: "{{ item.cipassword }}"
    ipconfig: "{{ item.ipconfig }}"
    serial: "{{ item.serial | default(omit) }}"
    vga: "{{ item.vga | default(omit) }}"
    state: present
  loop: "{{ proxmox_vms }}"
  loop_control:
    label: "{{ item.name }}"
  register: clone_vm
  failed_when: "'does not exist' not in clone_vm.msg and clone_vm.failed"
