---

main_username: user0
ntp_timezone: America/Los_Angeles

# -----
# arillso.system.users
# -----

users_list:
  - username: "{{ main_username }}"
    uid: 1000
    shell: /bin/bash
  - username: alice
    uid: 9999
    shell: /bin/bash

# -----
# grog.package
# -----
package_list:
  - name: git
  - name: curl

# -----
# jhaycr.luks_disks
# -----
luks_keyfile_path: /etc/luks.key
luks_disks_validate_serial: true

# -----
# IronicBadger.snapraid
# -----
snapraid_install: true
snapraid_runner: true

snapraid_data_disks:
  - path: /mnt/data1
    content: true
  - path: /mnt/data2
    content: true

snapraid_parity_disks:
  - path: /mnt/parity1
    content: false

snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - "*.bak"
  - /tmp/
  - backup/
  - downloads/
  - temp/
  - "aquota.group"
  - "aquota.user"
  - "snapraid.conf*"
  - "*.nfo"

snapraid_sync_schedule:
  minute: 0
  hour: 0

snapraid_scrub_schedule:
  minute: 5
  hour: 3
  weekday: 0

# -----
# tigattack.mergerfs
# -----
mergerfs_mounts:
  - path: /mnt/storage
    branches:
      - /mnt/data*
    options: defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=250G,fsname=mergerfs

# -----
# IronicBadger.docker_compose_generator
# -----
global_env_vars:
  - "PUID=1000"
  - "PGID=1000"
  - "TZ={{ ntp_timezone }}"

appdata_path: "/opt/appdata"
docker_compose_generator_output_path: "/home/{{ main_username }}/docker/monitoring"
containers:
  ###
  - service_name: influxdb
    active: true
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - "{{ appdata_path }}/influxdb_data:/var/lib/influxdb"