---

main_username: user0
ntp_timezone: America/Los_Angeles

docker_compose_templates_path: '../templates/docker/neo'

docker_storage_path: '/mnt/storage'
docker_home_compose_path: '/opt/docker'
docker_home_appdata_path: '/home/{{ main_username }}/docker/media-server/config/appdata'
docker_appdata_folders_to_own:
- maintainerr

# -----
# fuzzymistborn.autorestic
# -----
autorestic_download_latest_ver: false
autorestic_pinned_ver: 1.8.3
restic_download_latest_ver: false
restic_pinned_ver: 0.17.1

autorestic_config_user: "{{ main_username}}"
autorestic_user_directory: /home/"{{ main_username}}"
autorestic_run_check: true
autorestic_config_yaml:
  version: 2
  backends:
    local-home:
      type: local
      path: "{{ backup_path_local }}"
      key: "{{ secret_restic_repo_password }}"
    b2-neo-docker:
      type: b2
      path: 'emergent-thermodynamics:backup/neo/docker'
      env:
        B2_ACCOUNT_ID: "{{ secret_restic_repo_b2_account_id}}"
        B2_ACCOUNT_KEY: "{{ secret_restic_repo_b2_account_key }}"


# -----
# arillso.system.users
# -----

users_list:
  - username: "{{ main_username }}"
    uid: 1000
    shell: /bin/bash
  - username: alice
    uid: 9999
    shell: /bin/bash

# -----
# grog.package
# -----
package_list:
  - name: git
  - name: curl
  - name: iperf

# -----
# jhaycr.luks_disks
# -----
luks_keyfile_path: /etc/luks.key
luks_disks_validate_serial: true

# -----
# IronicBadger.snapraid
# -----
snapraid_install: true
snapraid_runner: true

snapraid_data_disks:
  - path: /mnt/data1
    content: true
  - path: /mnt/data2
    content: true

snapraid_parity_disks:
  - path: /mnt/parity1
    content: false

snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - "*.bak"
  - /tmp/
  - backup/
  - downloads/
  - temp/
  - "aquota.group"
  - "aquota.user"
  - "snapraid.conf*"
  - "*.nfo"

snapraid_runner_cron_jobs:
  - { job: '{{ snapraid_runner_command }}', name: 'snapraid_runner', weekday: '*', hour: '01', minute: '00' }


# -----
# tigattack.mergerfs
# -----
mergerfs_mounts:
  - path: /mnt/storage
    branches:
      - /mnt/data*
    options: defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=250G,fsname=mergerfs
