# roles/safe_shutdown/tasks/main.yml
---
- name: Detect init system
  ansible.builtin.command: ps --no-headers -o comm 1
  register: init_system
  changed_when: false
  become: true

- name: Set init system fact
  ansible.builtin.set_fact:
    is_systemd: "{{ init_system.stdout == 'systemd' }}"

- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: root
    group: root
  become: true
  loop:
    - { path: '/usr/local/sbin', mode: '0755' }
    - { path: '/var/log/safe-shutdown', mode: '0755' }

- name: Copy safe shutdown script
  ansible.builtin.template:
    src: safe-shutdown.sh.j2
    dest: /usr/local/sbin/safe-shutdown.sh
    mode: '0755'
    owner: root
    group: root
  become: true
  register: script_copy

- name: Configure systemd integration
  when: is_systemd
  block:
    - name: Install systemd service
      ansible.builtin.template:
        src: safe-shutdown.service.j2
        dest: /etc/systemd/system/safe-shutdown.service
        mode: '0644'
        owner: root
        group: root
      become: true
      register: systemd_service
    
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      become: true
      when: systemd_service.changed

    - name: Enable systemd service
      ansible.builtin.systemd:
        name: safe-shutdown
        enabled: yes
      become: true

- name: Install logrotate configuration
  ansible.builtin.template:
    src: safe-shutdown.logrotate.j2
    dest: /etc/logrotate.d/safe-shutdown
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Test shutdown script with dry-run
  ansible.builtin.command: /usr/local/sbin/safe-shutdown.sh --dry-run
  register: dry_run_test
  changed_when: false
  failed_when: 
    - dry_run_test.rc != 0
    - "'COMPLETION:SUCCESS' not in dry_run_test.stdout"
  become: true

- name: Display dry-run test output
  ansible.builtin.debug:
    var: dry_run_test.stdout_lines
  when: safe_shutdown_debug | default(false) | bool