# roles/safe_shutdown/tasks/main.yml
---
- name: Detect system type
  ansible.builtin.command: "pveversion"
  register: pve_check
  failed_when: false
  changed_when: false
  become: true

- name: Set system type fact
  ansible.builtin.set_fact:
    is_proxmox: "{{ pve_check.rc == 0 }}"

- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: root
    group: root
  become: true
  loop:
    - { path: '/usr/local/sbin', mode: '0755' }
    - { path: '/var/log/safe-shutdown', mode: '0755' }

- name: Copy safe shutdown script
  ansible.builtin.template:
    src: safe-shutdown.sh.j2
    dest: /usr/local/sbin/safe-shutdown.sh
    mode: '0755'
    owner: root
    group: root
  become: true
  register: script_copy

- name: Configure ProxMox integration
  when: is_proxmox
  block:
    - name: Get hook-script.conf stats if it exists
      ansible.builtin.stat:
        path: /etc/pve/hook-script.conf
      register: hook_script_conf
      become: true

    - name: Create hook-script.conf if it doesn't exist
      ansible.builtin.file:
        path: /etc/pve/hook-script.conf
        state: touch
        mode: '0640'
        owner: root
        group: www-data
        modification_time: preserve
        access_time: preserve
      become: true
      when: not hook_script_conf.stat.exists

    - name: Add shutdown hook to PVE configuration
      ansible.builtin.lineinfile:
        path: /etc/pve/hook-script.conf
        regexp: '^pre-shutdown:'
        line: 'pre-shutdown: /usr/local/sbin/safe-shutdown.sh'
        owner: root
        group: www-data
        mode: '0640'
      become: true

- name: Configure systemd integration
  when: not is_proxmox
  block:
    - name: Install systemd service
      ansible.builtin.template:
        src: safe-shutdown.service.j2
        dest: /etc/systemd/system/safe-shutdown.service
        mode: '0644'
        owner: root
        group: root
      become: true
      register: systemd_service
    
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      become: true
      when: systemd_service.changed

    - name: Enable systemd service
      ansible.builtin.systemd:
        name: safe-shutdown
        enabled: yes
      become: true

- name: Install logrotate configuration
  ansible.builtin.template:
    src: safe-shutdown.logrotate.j2
    dest: /etc/logrotate.d/safe-shutdown
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Test shutdown script with dry-run
  ansible.builtin.command: /usr/local/sbin/safe-shutdown.sh --dry-run
  register: dry_run_test
  changed_when: false
  failed_when: 
    - dry_run_test.rc != 0
    - "'COMPLETION:SUCCESS' not in dry_run_test.stdout"
  become: true

- name: Display dry-run test output
  ansible.builtin.debug:
    var: dry_run_test.stdout_lines
  when: safe_shutdown_debug | default(false) | bool