# Proxmox API credentials (use Ansible Vault for the password in production)
proxmox_api_host: "192.168.1.3"
proxmox_api_user: "root@pam"
proxmox_api_password: "{{ secret proxmox_password }}"
proxmox_node: "neo"

proxmox_images:
- os: debian
  release: bookworm
  url: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
  filename: "debian-12-genericcloud-amd64.qcow2"
  import: true
  template: true
  vmid: 9000
  name: debian-12-template
  storage: local-lvm
  memory: 1024
  cores: 1

proxmox_vms:
  - name: unifi-server
    vmid: 100
    template_vmid: 9000
    memory: 2048
    cores: 2
    net:
      net0: virtio,bridge=vmbr0
    pool: network
    ciuser: unifi
    cipassword: SuperSecurePass123
    sshkeys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    ipconfig0: "ip=192.168.1.50/24,gw=192.168.1.1"
    node: neo

# UniFi repo (APT)
unifi_version_repo: "https://www.ui.com/downloads/unifi/debian"